### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by PeuSouza** [PeuSouza/GSCMS-AnaPaula-Souza#2]
- [x] Instalar Git localmente

- [x]  Criar projeto local

- [x]  Criar repositório local e realizar commits

- [ ] Subir alterações para o repositório remoto o Fazer alterações no repositório da turma

@ramidedantas

**Comment by ramidedantas** [comment]
Joia, deixe aberto para a prática de Git e vá marcando.
